spring:
  datasource:
    url: jdbc:h2:mem:notebook
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring.session
  redis:
    host: localhost
    port: 6379